import { Geist, Geist_Mono , Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/header";
import Footer from "@/components/Footer/footer";
import AppSidebar from "@/components/Sidebar/AppSidebar";
  

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ["latin"],
  variable: "--font-plus-jakarta",
  weight: ["300", "400", "500", "600", "700", "800"],
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${plusJakarta.variable} antialiased`}
      >
        <Header />
        <div className="flex">
          <AppSidebar />
          <div className="flex-1">
             {children} 
          </div>
        </div>
      </body>
    </html>
  );
}
